version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      chapter4:
        ipv4_address: 172.20.0.1
    ports:
      - "9000:9000"

networks:
  chapter4:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

