# 서버용 Dockerfile
FROM ubuntu:24.04

# 필요한 패키지 설치
RUN apt-get update && apt-get install -y g++ && rm -rf /var/lib/apt/lists/*

# 소스 코드 복사
COPY Common.h .
COPY TCPServer.cpp .

# 서버 프로그램 컴파일
RUN g++ -o TCPServer TCPServer.cpp -lpthread

# 컨테이너 실행 시 서버 프로그램 실행
CMD ["./TCPServer"]
