version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      my_network:
        ipv4_address: 172.20.0.1
    ports:
      - "9000:9000"

  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      my_network:
        ipv4_address: 172.20.0.2

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
