# 서버용 Dockerfile
FROM ubuntu:24.04

# 필요한 패키지 설치
RUN apt-get update && apt-get install -y g++ && rm -rf /var/lib/apt/lists/*

# PING 테스트 용 패키지 및 그외 프로그램 관리 라이브러리 설치
RUN apt-get update && apt-get install -y inetutils-ping lsof gdb

# 소스 코드 복사
COPY Common.h .
COPY TCPServer.cpp .

# 서버 프로그램 컴파일 (디버깅 심볼 포함)
RUN g++ -g -o TCPServer TCPServer.cpp -lpthread

# 컨테이너 실행 시 서버 프로그램 실행
CMD ["./TCPServer"]
