version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      my_network:
        ipv4_address: 172.20.0.2

  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      - my_network

  client2:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      - my_network

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.21.0.0/16
