version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8082:8082"
    networks:
      my_network:
        ipv4_address: 172.21.0.2

  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      my_network:
        ipv4_address: 172.21.0.3

  client2:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      my_network:
        ipv4_address: 172.21.0.4

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.21.0.0/16
